[package]
name = "petgraph_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fst = "0.4.7"
itertools = "0.10.5"
petgraph = { version = "0.6.2", features = ["stable_graph"] }
